using QuickPulse.Explains;
using SharpBotz.Botz.BotModules;
using SharpBotz.Botz.BotModules.Batteries;

namespace SharpBotz.Tests.Docs.B_Bot.A_Modules.B_Battery;


[DocFile]
public class A_BatteryTests
{

    [Fact]
    [DocContent(
"""
A battery is where a bot stores excess power generated by a reactor.

It is created by specifying its capacity and a `ModuleId` (supplied as a string).
""")]
    [DocExample(typeof(A_BatteryTests), nameof(ConstructionExample))]
    [DocContent("Its initial charge is zero.")]
    public void Construction()
    {
        var battery = ConstructionExample();
        Assert.Equal(100, battery.Capacity);
        Assert.Equal(0, battery.Charge);
    }

    [CodeSnippet]
    private static Battery ConstructionExample() =>
         Battery.Named("battery").Capacity(100);

    [Fact]
    [DocContent("A battery with a capacity of zero or negative throws upon construction.")]
    public void Invalid()
    {
        Assert.Throws<ArgumentOutOfRangeException>(() => Battery.Named("battery").Capacity(0));
        var ex = Assert.Throws<ArgumentOutOfRangeException>(() => Battery.Named("battery").Capacity(-1));
        Assert.Equal("""
        capacity ('-1') must be a non-negative and non-zero value. (Parameter 'capacity')
        Actual value was -1.
        """, ex.Message);
    }

    [Fact]
    [DocContent(
"""
A battery with a capacity of 1 has a weight of 3.  
Every 25 extra capacity after the first 25 adds another 1 weight to the module. 
"""
    )]
    [DocBarChart(
        typeof(A_BatteryTests),
        nameof(WeightCurve),
        "Weight Curve",
        "Capacity",
        "Weight",
        0, 6)]
    public void WeightCurveTest()
    {
        foreach (var (capacity, weight) in WeightCurve)
        {
            Assert.Equal(weight, Battery.Named("battery").Capacity(capacity).Weight);
        }
    }

    private static readonly (int Capacity, int Weight)[] WeightCurve =
        [
            (1, 3),
            (25, 3),
            (35, 4),
            (51, 5),
            (76, 6),
            (100, 6)
        ];

    [Fact]
    [DocContent(
"""
Multiple batteries can be installed in a `ModuleRack`.

The rack's total energy capacity is the sum of all the batteries' capacities.
"""
    )]
    [DocExample(typeof(A_BatteryTests), nameof(MultipleExample))]
    public void Multiple()
    {
        var rack = MultipleExample();
        Assert.Equal(50, rack.BatteryCapacity);
    }

    [CodeSnippet]
    private static ModuleRack MultipleExample() =>
        ModuleRack.Create(
            Battery.Named("battery-one").Capacity(25),
            Battery.Named("battery-two").Capacity(25));
}
