using QuickPulse.Explains;
using SharpBotz.Botz.BotModules;
using SharpBotz.Botz.BotModules.Batteries;

namespace SharpBotz.Tests.Docs.B_Bot.A_Modules.B_Battery;


[DocFile]
public class A_BatteryTests
{

    [Fact]
    [DocContent(
"""
A battery is where a Bot stores excess power generated by a Reactor.

It is created by passing in it's capacity along with a ModuleId (supplied as string).
""")]
    [DocExample(typeof(A_BatteryTests), nameof(ConstructionExample))]
    [DocContent("It's initial Charge is set to zero.")]
    public void Construction()
    {
        var battery = ConstructionExample();
        Assert.Equal(100, battery.Capacity);
        Assert.Equal(100, battery.AvailableCapacity);
        Assert.Equal(0, battery.Charge);
    }

    [CodeSnippet]
    private static Battery ConstructionExample() =>
         Battery.Named("battery").Capacity(100);

    [Fact]
    [DocContent("A battery with a capacity of zero or negative throws upon construction.")]
    public void Invalid()
    {
        Assert.Throws<ArgumentOutOfRangeException>(() => Battery.Named("battery").Capacity(0));
        var ex = Assert.Throws<ArgumentOutOfRangeException>(() => Battery.Named("battery").Capacity(-1));
        Assert.Equal("""
        capacity ('-1') must be a non-negative and non-zero value. (Parameter 'capacity')
        Actual value was -1.
        """, ex.Message);
    }

    [Fact]
    [DocContent(
"""
A battery with a capacity of 1 has a weight of 3.  
Every 25 extra capacity after the first 25 adds another 1 weight to the module. 
"""
    )]
    [DocCode(
"""
xychart-beta
    title "Weight Curve"
    x-axis "Capacity" [1, 25, 35, 51, 76, 100]
    y-axis "Weight" 0 --> 6
    bar [3, 3, 4, 5, 6, 6]
""", "mermaid")]
    public void WeightCurve()
    {
        var battery = Battery.Named("battery").Capacity(1);
        Assert.Equal(3, battery.Weight);
        battery = Battery.Named("battery").Capacity(25);
        Assert.Equal(3, battery.Weight);
        battery = Battery.Named("battery").Capacity(35);
        Assert.Equal(4, battery.Weight);
        battery = Battery.Named("battery").Capacity(51);
        Assert.Equal(5, battery.Weight);
        battery = Battery.Named("battery").Capacity(76);
        Assert.Equal(6, battery.Weight);
        battery = Battery.Named("battery").Capacity(100);
        Assert.Equal(6, battery.Weight);
    }

    [Fact]
    [DocContent(
"""
Multiple batteries can be installed in a ModuleRack.

The total energy capacity of the rack is then the sum of all Battery capacities.
"""
    )]
    [DocExample(typeof(A_BatteryTests), nameof(MultipleExample))]
    public void Multiple()
    {
        var rack = MultipleExample();
        Assert.Equal(50, rack.BatteryCapacity);
    }

    [CodeSnippet]
    private static ModuleRack MultipleExample() =>
        ModuleRack.Create(
            Battery.Named("battery-one").Capacity(25),
            Battery.Named("battery-two").Capacity(25));
}